[options]
  colorscheme = "molokai"
  enable_guicolors = true
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  autocomplete_method = "deoplete"
  autocomplete_parens = false
  bootstrap_before = "custom#before"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "autocomplete"
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "shell"
  default_position = "bottom"
  default_height = 30
  default_shell = "terminal"


[[layers]]
  name = "tmux"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "fzf"

[[layers]]
  name = "lsp"

[[layers]]
  name = "format"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#dockerfile"

[[custom_plugins]]
  name = 'hashivim/vim-terraform'

[[custom_plugins]]
  name = 'juliosueiras/vim-terraform-completion'
